### ISSUE TITLE
Does it works with Windows 11 ?

### ISSUE THREAD

**Issue by MilesTEG1** [Upinel/BetterRDP#1]
Hello, I read your guide for iGPU pass through for proxmox, and I found this repository.
Do you think this will works with windows 11 (pro) ?

thanks in advance

**Comment by Upinel** [comment]
it should. Win 10 & win 11 is not that different in terms of core system.

**Comment by joan-novestecnologies** [comment]
Hi! 

Could you please provide the link to the guide?

I am walking the same path, Win 11 Virtual Machines
