### ISSUE TITLE
for 50fps

### ISSUE THREAD

**Issue by brusezot** [Upinel/BetterRDP#2]
Hi thanks for your repo but which value to 50FPS in RDP ? 

Best regards,

**Comment by Upinel** [comment]
;Optimize the capture frame rate for RDP sessions to achieve 60 FPS.
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services]
"VGOptimization_CaptureFrameRate"=dword:0000003c
