### ISSUE TITLE
Rdp having glitchy screen

### ISSUE THREAD

**Issue by vassooooo** [Upinel/BetterRDP#3]
After running this on multiple different devices, it'd been like this. How can I solve this? 
![image-37](https://github.com/user-attachments/assets/d124c530-2452-414d-8fa8-b5be40d12436)
![image-39](https://github.com/user-attachments/assets/25f476c5-e3c1-4a32-9901-96d57a2c6619)

**Comment by TamTamCha** [comment]
https://superuser.com/questions/1832807/weird-graphical-glitch-in-remote-desktop-connection

Maybe Disable Persistent Bitmap Caching?

**Comment by Upinel** [comment]
Can you share your host environment? e.g. your GPU, iGPU or hypervisor technology if you are running inside a VM.

**Comment by nifanfa** [comment]
How did you solve this problem? Please share!!!

**Comment by rwasef1830** [comment]
After years I still didn't solve it. Rdp 4 4 4 mode is just bad and if you turn off 4 4 4 mode you get software decode. I'm trying to find alternative self hosted solution like moonlight and sunshine but it had its own problems

**Comment by nifanfa** [comment]
> After years I still didn't solve it. Rdp 4 4 4 mode is just bad and if you turn off 4 4 4 mode you get software decode. I'm trying to find alternative self hosted solution like moonlight and sunshine but it had its own problems

Does that mean disabling 444 mode will solve the problem? Yes, Moonlight is indeed a better choice, especially for remote gaming. However, RDP offers the best image quality and uses less bandwidth

**Comment by rwasef1830** [comment]
If you disable 444 you solve the problem by losing 60 fps and hw encode decode fully. It's a solution which defeats the purpose.

**Comment by nifanfa** [comment]
> After years I still didn't solve it. Rdp 4 4 4 mode is just bad and if you turn off 4 4 4 mode you get software decode. I'm trying to find alternative self hosted solution like moonlight and sunshine but it had its own problems

Have you tried this? does this work?

> https://superuser.com/questions/1832807/weird-graphical-glitch-in-remote-desktop-connection
> 
> Maybe Disable Persistent Bitmap Caching?

**Comment by rwasef1830** [comment]
Tried. Does not help. Only delays slightly.

Funny thing Ms added hevc support to rdp but they paywalled it to windows 365 azure virtual desktop.. no own windows access to it.

**Comment by rwasef1830** [comment]
https://learn.microsoft.com/en-us/azure/virtual-desktop/graphics-encoding

They can give it to everyone but they choose not to. They want you to rent cloud PC.

**Comment by nifanfa** [comment]
> https://learn.microsoft.com/en-us/azure/virtual-desktop/graphics-encoding
> 
> They can give it to everyone but they choose not to. They want you to rent cloud PC.

Ahhh that sucks. I'm wondering if there's any alternative with image quality as good as mstsc that can be accessed through a browser. TightVNC+NoVNC works, but VNC performance is too poor... RDP is good, but it's unusable for FPS games.

**Comment by rwasef1830** [comment]
Sunshine is good but buggy. The virtual display driver with it sucks and it needs some manual scripting to switch monitors. I didn't succeed to get it working as I want.

**Comment by nifanfa** [comment]
> Sunshine is good but buggy. The virtual display driver with it sucks and it needs some manual scripting to switch monitors. I didn't succeed to get it working as I want.

Try HDMI emulator? like

<img width="550" height="550" alt="Image" src="https://github.com/user-attachments/assets/d34f6a07-7d1e-4472-a277-b78b9a177018" />

**Comment by rwasef1830** [comment]
don't have and not easily available where i am
